import {
  Gauge,
  Target,
  Brain,
  Grid3X3,
  MemoryStick,
  BrainCircuit,
  Shield,
  Eye,
  Wind,
  Crosshair,
  Shuffle,
  type LucideIcon,
} from "lucide-react";
import type { GameId } from "@/lib/storage/types";

export interface GameMetadata {
  id: GameId;
  title: string;
  href: string;
  icon: LucideIcon;
  color: string;
  desc: string;        // 用于导航栏的简短功能描述
  description: string; // 用于首页的详细规则描述
  benefit: string;     // 核心训练获益点
  duration: string;    // 显示的时长，如 "约 1 分钟"
  minutes: number;     // 计划生成器所需的估算分钟数，如 1, 2, 3
  difficulty: "入门" | "中等" | "困难";
}

export const GAMES_META: Record<GameId, GameMetadata> = {
  "reaction-time": {
    id: "reaction-time",
    title: "反应速度测试",
    href: "/reaction-time",
    icon: Gauge,
    color: "#D4A832",
    desc: "基础神经反应速度",
    description: "屏幕变绿瞬间点击，测测你的大脑处理速度。",
    benefit: "了解你的大脑「基础网速」",
    duration: "约 1 分钟",
    minutes: 1,
    difficulty: "入门",
  },
  "attention-span": {
    id: "attention-span",
    title: "专注力追踪",
    href: "/attention-span",
    icon: Target,
    color: "#8FB8A8",
    desc: "持续注意稳定性",
    description: "按住移动圆点，测试你的持续注意稳定性。",
    benefit: "像做一组注意力的「平板支撑」",
    duration: "约 2 分钟",
    minutes: 2,
    difficulty: "中等",
  },
  flanker: {
    id: "flanker",
    title: "抗干扰训练",
    href: "/flanker",
    icon: Crosshair,
    color: "#5A9DE0",
    desc: "选择性注意训练",
    description: "在干扰箭头中判断中心方向，训练选择性注意。",
    benefit: "帮你在嘈杂环境保持专注",
    duration: "约 2 分钟",
    minutes: 2,
    difficulty: "中等",
  },
  "task-switching": {
    id: "task-switching",
    title: "专注切换",
    href: "/task-switching",
    icon: Shuffle,
    color: "#A87AD4",
    desc: "认知灵活性训练",
    description: "在两套规则间快速切换，训练认知灵活性。",
    benefit: "减少「做着 A 想起 B」的思维跳跃",
    duration: "约 2 分钟",
    minutes: 2,
    difficulty: "中等",
  },
  "stroop-test": {
    id: "stroop-test",
    title: "专注拉回",
    href: "/stroop-test",
    icon: Brain,
    color: "#D4847C",
    desc: "认知抑制与冲突",
    description: "颜色与文字的冲突，测测你的认知抑制能力。",
    benefit: "3 分钟拉回走神的大脑",
    duration: "约 3 分钟",
    minutes: 3,
    difficulty: "中等",
  },
  "schulte-grid": {
    id: "schulte-grid",
    title: "舒尔特方格",
    href: "/schulte-grid",
    icon: Grid3X3,
    color: "#5A9DE0",
    desc: "视觉搜索与注意广度",
    description: "在乱序数字中快速按序点击，训练注意力广度。",
    benefit: "开工前热身，像运动员上场前的拉伸",
    duration: "约 2 分钟",
    minutes: 2,
    difficulty: "入门",
  },
  "nback-memory": {
    id: "nback-memory",
    title: "工作记忆",
    href: "/nback-memory",
    icon: MemoryStick,
    color: "#A87AD4",
    desc: "工作记忆训练",
    description: "工作记忆的黄金标准任务，挑战你的信息保持能力。",
    benefit: "提升你同时处理多件事的能力",
    duration: "约 3 分钟",
    minutes: 3,
    difficulty: "困难",
  },
  "digit-span": {
    id: "digit-span",
    title: "数字广度",
    href: "/digit-span",
    icon: BrainCircuit,
    color: "#9B7BC7",
    desc: "记忆容量评估",
    description: "经典记忆容量测试，测测你能记住几位数字。",
    benefit: "测测你的大脑「内存条」有多大",
    duration: "约 3 分钟",
    minutes: 3,
    difficulty: "中等",
  },
  "go-nogo": {
    id: "go-nogo",
    title: "冲动控制",
    href: "/go-nogo",
    icon: Shield,
    color: "#D4847C",
    desc: "抑制冲动反应训练",
    description: "看到绿色点击，红色不点击，测测你的冲动控制能力。",
    benefit: "训练「停下来的能力」，减少冲动",
    duration: "约 3 分钟",
    minutes: 3,
    difficulty: "中等",
  },
  "focus-gaze": {
    id: "focus-gaze",
    title: "凝视启动",
    href: "/focus-gaze",
    icon: Eye,
    color: "#D4A832",
    desc: "激活蓝斑核",
    description: "盯住一点 30–60 秒，激活蓝斑核，快速进入专注状态。",
    benefit: "30 秒专注「开关」，开工前启动大脑",
    duration: "约 1 分钟",
    minutes: 1,
    difficulty: "入门",
  },
  "breathing-478": {
    id: "breathing-478",
    title: "4-7-8 呼吸法",
    href: "/breathing-478",
    icon: Wind,
    color: "#6BA7A8",
    desc: "放松减压练习",
    description: "跟随指引呼吸，激活副交感神经，快速放松身心。",
    benefit: "焦虑时的一键「降温」",
    duration: "约 2 分钟",
    minutes: 2,
    difficulty: "入门",
  },
};

export const GAMES_LIST = Object.values(GAMES_META);
